### ISSUE TITLE
dupe bug with iron golem on island

### ISSUE THREAD

**Issue by amarcais53** [BentoBoxWorld/Limits#128] opened 2021-04-15 17:57 UTC
#### Describe the bug
Hello , the bug is simple and working only on islands , take a Jack'O lantern put iron blocks to make a golem and put the jacko lantern and the bug apear, golem is spawning and the blocks are not removed

#### Steps to reproduce the behavior
go on your island
do an iron golem with Jack'O lantern

#### Expected behavior
usually when a golem spawn every iron blocks and the jack 'o lantern should be removed

#### Screenshots and videos (Optional)
https://www.youtube.com/watch?v=l2fOadeunVI

##### Output of `/bbox version` (Mandatory)
[19:56:44 INFO]: Serveur Invalide (PURPUR) 1.16.5.
[19:56:44 INFO]: Version de BentoBox : 1.16.1-SNAPSHOT-b2010
[19:56:44 INFO]: Base de données : JSON
[19:56:44 INFO]: Mondes de jeu chargés :
[19:56:44 INFO]: bskyblock_world (BSkyBlock) : Overworld, Nether, End*
[19:56:44 INFO]: Addons chargés :
[19:56:44 INFO]: Bank 1.3.0 (ENABLED)
[19:56:44 INFO]: Biomes 1.14.1-SNAPSHOT-b204 (ENABLED)
[19:56:44 INFO]: Border 3.0.0-SNAPSHOT-b86 (ENABLED)
[19:56:44 INFO]: BSkyBlock 1.14.4-SNAPSHOT-b682 (ENABLED)
[19:56:44 INFO]: Challenges 0.8.5-SNAPSHOT-b444 (ENABLED)
[19:56:44 INFO]: Chat 1.1.3 (ENABLED)
[19:56:44 INFO]: ControlPanel 1.13.1-SNAPSHOT-b49 (ENABLED)
[19:56:44 INFO]: Level 2.6.1 (ENABLED)
[19:56:44 INFO]: Likes 2.2.0-SNAPSHOT-b55 (ENABLED)
[19:56:44 INFO]: Limits 1.15.6-SNAPSHOT-b254 (ENABLED)
[19:56:44 INFO]: MagicCobblestoneGenerator 2.4.0-SNAPSHOT-b213 (ENABLED)
[19:56:44 INFO]: Warps 1.10.2 (ENABLED)
```
_______
```

#### Plugins (Optional)
[19:57:06 INFO]: Plugins (58): AnimatedScoreboard, AntiAutoClick, AureliumSkills, BattlePass, BeautyQuests, BentoBox, BungeeGuard, Citizens, CommandHook, DeluxeChat, DeluxeMenus, DyedBackpacks, Essentials, EssentialsSpawn, ExoticGarden, ExtraTools, FastChunkPregenerator, FluffyMachines, GeinsBasics, GoldenCrates, HolographicDisplays, HolographicExtension, InfinityExpansion, Jobs, JukeBox, LiteXpansion, LuckPerms, Maintenance, MessageAnnouncer, MineableSpawners, MMOItems, Multiverse-Core, MythicLib, MythicMobs, NexEngine, NoteBlockAPI, OldCombatMechanics, PlaceholderAPI, Playtimes*, ProtocolLib, Rankup, SFCalc, Shop, ShopGUIPlus, Shopkeepers, Slimefun, spark, TAB, TradeSystem, Vault, VoidGenerator, WildStacker, WitherSound*, WorldEdit, WorldGuard, WorldGuardExtraFlags, XPBoost, zAuctionHouseV3
```
_______
```

**Comment by tastybento** [comment] 2021-04-17 15:59
Duplicate of #127

**Closed by tastybento** 2021-04-17 15:59 UTC
