### ISSUE TITLE
Can't spawn iron golem

### ISSUE THREAD

**Issue by OverBrave** [BentoBoxWorld/Limits#140] opened 2021-08-20 22:35 UTC
### Expected behavior

Normally, the IRON Golem needs to spawn. But the console is getting an error.

### Observed/Actual behavior

![image](https://user-images.githubusercontent.com/47111280/130299693-432602a8-41d9-4794-9e69-a536dac8f14c.png)

### Steps/models to reproduce

Try to spawn Iron Golem on Island.

### BentoBox version

![image](https://user-images.githubusercontent.com/47111280/130299624-38e7f089-9317-4ae9-bb94-b74905271968.png)

**Comment by tastybento** [comment] 2021-08-21 00:05
Duplicate of #135 . Please use 1.7.1. https://github.com/BentoBoxWorld/Limits/releases/tag/1.7.1

**Closed by tastybento** 2021-08-21 00:05 UTC
